version: "3.7"

services:
  frontend:
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: Dockerfile
    image: baquerizogo-personal-page
    container_name: baquerizogo-personal-page
    volumes:
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    restart: always
    networks:
      - baquerizogo

networks:
  baquerizogo:
    name: baquerizogo-net
    driver: bridge
